### PR TITLE
Add `is_supplied()`

### PR DESCRIPTION
**Pull request by lionel-**

### CODE REVIEW

**Comment by hadley** [comment]
`is_present()` feels like a more natural inverse of `is_missing()` to me

**Comment by lionel-** [comment]
Good point. Should this be an rlang function actually?

**Comment by hadley** [comment]
Maybe we could make it more specific to lifecycle so we don't have that conundrum? Like `is_deprecated_arg()` or similar? If we do that, we should probably remove the description of the sentinel actually is so we can change it in the future.

**Comment by lionel-** [comment]
I asked about rlang only so we could avoid adding a new function to lifecycle. If we add one anyway, we could test how `is_present()` feels in lifecycle, and if we add it to rlang later on, reexport it from there.

**Pull request merged**
