### PR TITLE
Make `is_direct()` work the same way in CMD check

### LINKED ISSUE #142: Logic slightly wrong for `is_direct()` in `deprecate_warn()`?
This test in the admiral package fails when run in from revdepcheck, but not when run locally:

```R
test_that("derive_var_agegr_fda Test 1: A warning is issued if `derive_var_agegr_fda()` is called", { # nolint
  with_options(lifecycle_verbosity = "warning", {
    expect_warning(
      derive_var_agegr_fda(admiral_dm, age_var = AGE, new_var = AGEGR1),
      "deprecated",
      fixed = TRUE
    )
  })
})
```

Presumably because of the on CRAN check, which should only be used in `deprecate_soft()`?

### PR DESCRIPTION
**Pull request by lionel-**
Closes #142

I think it should work the same way:

- Interactively (topenv is global)
- In `test()`
- In CMD check

### CODE REVIEW

**Comment by hadley** [comment]
This loses the guarantee that "a soft deprecation can never break a revdep on CRAN". Are we ok with that? If so, will need an update to the NEWS bullet I wrote.

**Comment by lionel-** [comment]
IIUC, the failure mode you are thinking of is when a soft-deprecated feature is directly used in tests within a no-warning expectation?

It'd be nice to avoid that, but I think having consistent behaviour in different settings is probably more important.

Also you're going to change `expect_warning(x, NA)` so that it doesn't fail for lifecycle warnings right?

**Comment by hadley** [comment]
Yeah, good point. I'll tweak testthat.

**Comment by hadley** [comment]
I was also thinking of the case of using it in examples which sometimes appears to cause R CMD check failures.

**Comment by lionel-** [comment]
We use `deprecate_warn()` in the lifecycle examples, so at least these warnings should be safe to use.

I'll try and find out exactly which warning cause CMD check failures tomorrow.

**Pull request merged**
