### PR TITLE
Update diagram to use superseded

### PR DESCRIPTION
**Pull request by batpigandme**
* Use superseded in orange, rather than retired in blue for the lifecycle diagram.

### CODE REVIEW

**Comment by hadley** [comment]
I think we want to use blue? This is the version I presented at conf:

Screenshot 2020-03-12 at 7 43 24 AM

**Comment by batpigandme** [comment]
OK. We're using orange for badge itself right now.

**Comment by hadley** [comment]
Doh. We need to make it blue. cc @lionel-

**Comment by batpigandme** [comment]
> Doh. We need to make it blue. cc @lionel-

Did this as well.

**Comment by lionel-** [comment]
Thanks!

**Pull request merged**
