### PR TITLE
Remove extra <tspan>...</tspan>in the middle of the word "deprecated"

### PR DESCRIPTION
**Pull request by Bisaloo**
The text on the figure in https://lifecycle.r-lib.org/articles/stages.html looks really off (see screenshot below because this might be system dependent(???)): 

image

While looking at the source of the svg, I noticed an extra `<tspan>...</tspan>` in the middle of the word "deprecated".

https://github.com/r-lib/lifecycle/commit/1518b7e8e549f803520e2e1e15701763ffe93c0a fixes this

https://github.com/r-lib/lifecycle/commit/0dbd17a96b7ae49b9b114fea439288ab95f9da98 goes a step further by centering the text vertically and horizontally inside the boxes (see for example how experimental looks awkward in the attached screenshot).

Please let me know if you'd like me to only submit the first commit but not the second.

### CODE REVIEW

**Comment by hadley** [comment]
It looks like the second change actually makes it look worse in some situations, e.g. the github preview:

Screenshot 2021-02-12 at 8 07 29 AM

**Comment by Bisaloo** [comment]
My guess is that this is browser-dependent since it looks better for me in the GitHub preview:

image

Maybe it would be safer to cherry-pick only for first commit until we figure out what is going on? You want me to do it?

**Comment by hadley** [comment]
Yeah, that'd be great, thanks.

**Comment by Bisaloo** [comment]
@hadley, done (pinging because GitHub doesn't notify on force pushes).

**Comment by hadley** [comment]
FWIW I did get an notification

Screenshot 2021-02-12 at 10 48 36 AM

**Comment by hadley** [comment]
Hmm actually it looks worse for me:

Screenshot 2021-02-12 at 10 49 29 AM

**Comment by Bisaloo** [comment]
After some testing, it looks like some properties of textSpan are not properly standardized across browsers. So I ended up removing them and the text is now programmatically centered via dedicated properties (https://stackoverflow.com/questions/5546346/how-to-place-and-center-text-in-an-svg-rectangle)

**Comment by Bisaloo** [comment]
You can view the problem that triggered this issue in Firefox btw. Using chromium, I seem to get the same result as you.

**Comment by hadley** [comment]
I think if you could restore `font-family="Helvetica Neue"` it'll be good.

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
