### PR TITLE
Format bullets with cli

### LINKED ISSUE #141: Warnings lose formatting
with CRAN lifecycle:

``` r
tidyselect::all_of("x")
#> Warning: Using `all_of()` outside of a selecting function was deprecated in tidyselect 1.2.0.
#> See details at<https://tidyselect.r-lib.org/reference/faq-selection-context.html>
#> [1] "x"
```

<sup>Created on 2022-09-25 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
with dev lifeycle:

``` r
tidyselect::all_of("x")
#> Warning: Using `all_of()` outside of a selecting function was deprecated in tidyselect
#> 1.2.0. See details
#> at<https://tidyselect.r-lib.org/reference/faq-selection-context.html>
#> [1] "x"
```

Probably due to 705e6dc55800358f0c8346b938dee3029ee56c2d

### PR DESCRIPTION
**Pull request by lionel-**
Closes #141

### CODE REVIEW

**Comment by hadley** [comment]
This isn't quite enough:

``` r
name <- "foo"
paste_lines <- function(...) paste(c(...), collapse = "\n")
lifecycle::deprecate_warn("1.1.0",
  what = I("Use of bare predicate functions"),
  with = I("wrap predicates in `where()`"),
  details = paste_lines(
    "  # Was:",
    glue::glue("  data %>% select({name})"),
    "",
    "  # Now:",
    glue::glue("  data %>% select(where({name}))")
  )
)
#> Warning: Use of bare predicate functions was deprecated in <NA> 1.1.0.
#> Please use wrap predicates in `where()` instead.
#> # Was: data %>% select(foo)
#> 
#> # Now: data %>% select(where(foo))
#> ℹ The deprecated feature was likely used in the base package.
#>   Please report the issue to the authors.
```

<sup>Created on 2022-09-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Was previously:


``` r
name <- "foo"
paste_lines <- function(...) paste(c(...), collapse = "\n")
lifecycle::deprecate_warn("1.1.0",
  what = I("Use of bare predicate functions"),
  with = I("wrap predicates in `where()`"),
  details = paste_lines(
    "  # Was:",
    glue::glue("  data %>% select({name})"),
    "",
    "  # Now:",
    glue::glue("  data %>% select(where({name}))")
  )
)
#> Warning: Use of bare predicate functions was deprecated in <NA> 1.1.0.
#> Please use wrap predicates in `where()` instead.
#>   # Was:
#>   data %>% select(foo)
#> 
#>   # Now:
#>   data %>% select(where(foo))
```

<sup>Created on 2022-09-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by lionel-** [comment]
I noticed that while updating dplyr snapshots. But I don't think we can do better though, it seems like a necessary behaviour change where previously you had to supply formatted `details`, and now the details must be bullet lines.

@gaborcsardi Is there any way we could prevent cli from reformatting lines? Perhaps with `I()`?

E.g. we now have:

```r
cli::cli_abort(c(
  "Title",
  I("Please update your code:
  # Before
  foo()

  # After:
  bar()")
))
#> Error:
#> ! Title
#> Please update your code: # Before foo() #
#> After: bar()
```

Could this be:

```r
#> Error:
#> ! Title
#> Please update your code:
#>   # Before
#>   foo()
#>
#>   # After:
#>   bar()
```

**Comment by gaborcsardi** [comment]
I don't think that syntax is an option:
```r
❯ identical(c("foo", I("bar")), c("foo", "bar"))
[1] TRUE
```

But in general `format_bullets()` etc. are quite magical already, so I would rather create an escape hatch that supports arbitrary cli formatting. IDK what the syntax would be, `I()` does not work, unfortunately. The same for anything similar, because `c()` drops the classes.

**Comment by gaborcsardi** [comment]
We could have something like 
```
cli_bullets(
  "!r" = "...",
  "ir" = "..."
)
```

`"r"` meaning raw, i.e. w/o any reformatting.

**Comment by lionel-** [comment]
oh yeah of course, good point.

`"*r"` seems like a good idea. I'm just slightly worried about making it harder to extend the UI in the future. Maybe we could use hyphens to separate options. And also fully spell out "raw" for readability.

```r
cli_bullets(
  "!-raw" = "...",
  "i-raw" = "..."
)
```

**Comment by gaborcsardi** [comment]
I don't mind, but the UI is already abbreviated and we don't write `"info" = "..."`, but `"i" = "..."`. So it looks weird to me if we spell out some parts, but not the others. 

Re. extensibility, I think if we add "raw" items, that's pretty extensible, so hopefully we don't need to extend the UI any more.

**Comment by lionel-** [comment]
I think it's ok if the abbreviated part is the main UI, and then options which are rarely used are fully spelled out for readability.

**Comment by lionel-** [comment]
@hadley In order to fully delegate formatting to cli, is it ok to proceed with this behaviour change that requires downstream packages to update their `details` argument?

Switching from `paste_line()` to `c()` is fairly easy: https://github.com/tidyverse/dplyr/commit/1ea101d4b3883b1eed981b808e03f5e56d1c493e#

Switching from a raw string to `c()` will be a bit annoying until we have an updated cli version that accepts raw text though, because the string needs to be split up by line.

Until packages have updated their `details` arguments, the deprecation messages will look mangled if users end up with mismatched versions, but there should not be any errors. I did a github search and most `details` arguments are single-line. There are a few multi-line ones, but only dplyr supplies these as a single string. Interestingly, the other packages (dm, vembedr, and mrgsolve) supply a list of bullets (the last two even supply info bullets). So it seems the bullets interface is the one that people already expect for multiple lines.

**Comment by hadley** [comment]
What's the advantage of using cli in lifecycle now? Could we revert #136 and reconsider using cli in the future?

**Comment by lionel-** [comment]
The advantage of switching to cli is that we have a clean model for formatting lines.

The only downside to switching now that I can see is that a single deprecated feature in CRAN dplyr will get a mangled message for a little while. This is an obscure `funs()` feature that was deprecated a long time ago so I'm not worried about it.

**Comment by hadley** [comment]
It also mangles all the deprecation messages in dev tidyselect, and making that rely on the dev version of lifecycle is going to make the in process release more complex. I really think it'd be best to back out of this change and do it later on when we don't have so many package releases in motion.

**Comment by lionel-** [comment]
If we push to CRAN a paste-pattern in widely exposed deprecated features, that will make it much harder to move to cli later on.

I think we just need to fix dev tidyselect to use bullets since they already work with CRAN lifecycle. I've done this in https://github.com/r-lib/tidyselect/pull/321

**Comment by hadley** [comment]
You'll also need to fix purrr. And potentially any number of other packages.

**Comment by lionel-** [comment]
> And potentially any number of other packages.

See comment above:

> I did a github search and most details arguments are single-line. There are a few multi-line ones, but only dplyr supplies these as a single string. Interestingly, the other packages (dm, vembedr, and mrgsolve) supply a list of bullets (the last two even supply info bullets). So it seems the bullets interface is the one that people already expect for multiple lines.

I'm happy to fix dev purrr before it goes to CRAN.

**Comment by hadley** [comment]
Ok, if you fix purrr I'm fine with it.

**Pull request merged**
